"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { CSSProperties } from "react";
import { Captions, ChevronLeft, ChevronRight, Expand, Globe2, Info, Menu, Pause, PictureInPicture, Play, Search, Settings, Volume2, X } from "lucide-react";

import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";

import { publicMovies, formatDuration, type Locale, type ContentType, type Genre, type VideoSource, type Movie, type Episode, type Series } from "@/lib/catalog";

const copy = {
  ar:{movies:"أفلام",series:"مسلسلات",searchMovies:"ابحث عن فيلم...",searchSeries:"ابحث عن مسلسل...",watch:"شاهد الآن",details:"التفاصيل",fresh:"جديد",top:"الأعمال المتاحة",legal:"محتوى مرخّص ومتاح قانونيًا",rights:"حقوق ومصدر المحتوى",emptyMovies:"لا توجد أفلام مطابقة لهذا التصنيف حاليًا.",emptySeries:"لا توجد مسلسلات متاحة حاليًا.",movie:"فيلم",seriesOne:"مسلسل",close:"إغلاق",source:"صفحة المصدر والترخيص",menu:"القائمة",quality:"الجودة",subtitles:"الترجمة",off:"إيقاف الترجمة",nowPlaying:"يعرض الآن",noSubtitles:"لا توجد ترجمة مرخّصة لهذا العمل",previous:"الحلقة السابقة",next:"الحلقة التالية",seasons:"المواسم"},
  en:{movies:"Movies",series:"Series",searchMovies:"Search movies...",searchSeries:"Search series...",watch:"Watch now",details:"Details",fresh:"New",top:"Available titles",legal:"Licensed and legally available",rights:"Content rights & source",emptyMovies:"No movies currently match this genre.",emptySeries:"No series are available right now.",movie:"Movie",seriesOne:"Series",close:"Close",source:"Source and license page",menu:"Menu",quality:"Quality",subtitles:"Subtitles",off:"Off",nowPlaying:"Now playing",noSubtitles:"No licensed subtitles are available for this title",previous:"Previous episode",next:"Next episode",seasons:"Seasons"},
};

const genreLabels:Record<Genre,{ar:string;en:string;target:number}>={
  action:{ar:"أكشن",en:"Action",target:100}, horror:{ar:"رعب",en:"Horror",target:100}, comedy:{ar:"كوميديا",en:"Comedy",target:100}, drama:{ar:"دراما",en:"Drama",target:50}, romance:{ar:"رومانسي",en:"Romance",target:50}, thriller:{ar:"إثارة",en:"Thriller",target:50}, crime:{ar:"جريمة",en:"Crime",target:50}, mystery:{ar:"غموض",en:"Mystery",target:50}, adventure:{ar:"مغامرات",en:"Adventure",target:50}, scifi:{ar:"خيال علمي",en:"Science Fiction",target:50}, fantasy:{ar:"فانتازيا",en:"Fantasy",target:50}, war:{ar:"حربي",en:"War",target:50}, western:{ar:"غربي",en:"Western",target:50}, family:{ar:"عائلي",en:"Family",target:50}, animation:{ar:"رسوم متحركة",en:"Animation",target:50}, musical:{ar:"موسيقي",en:"Musical",target:50}, history:{ar:"تاريخي",en:"History",target:50}, biography:{ar:"سيرة ذاتية",en:"Biography",target:50}, sport:{ar:"رياضي",en:"Sport",target:50},
};

// No series is public until a complete season passes the item-level rights gate.
const seriesCatalog: Series[] = [];

function formatClock(seconds:number){if(!Number.isFinite(seconds))return"0:00";const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=Math.floor(seconds%60);return h?`${h}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:`${m}:${String(s).padStart(2,"0")}`}

function CineyahPlayer({movie,locale,onClose}:{movie:Movie;locale:Locale;onClose:()=>void}){
  const text=copy[locale],videoRef=useRef<HTMLVideoElement>(null);
  const lastSavedRef=useRef(-1),pendingQualityRef=useRef<{time:number;playing:boolean}|null>(null);
  const [playing,setPlaying]=useState(false),[time,setTime]=useState(0),[duration,setDuration]=useState(movie.runtimeMinutes*60),[volume,setVolume]=useState(1),[quality,setQuality]=useState(movie.sources[0].label),[panel,setPanel]=useState<"quality"|"subs"|null>(null),[subtitle,setSubtitle]=useState<"ar"|"en"|"off">(movie.subtitles.some(s=>s.lang==="ar")?"ar":"off"),[mediaError,setMediaError]=useState(false);
  const source=movie.sources.find(s=>s.label===quality)??movie.sources[0];
  useEffect(()=>{const video=videoRef.current;if(!video)return;const saved=Number(localStorage.getItem(`cineyah:progress:${movie.id}`)||0);if(saved>15&&saved<movie.runtimeMinutes*60-60)video.currentTime=saved},[movie.id,movie.runtimeMinutes]);
  useEffect(()=>{const video=videoRef.current;if(!video)return;for(const track of Array.from(video.textTracks))track.mode=track.language===subtitle?"showing":"disabled"},[subtitle]);
  const applySubtitle=()=>{const video=videoRef.current;if(!video)return;for(const track of Array.from(video.textTracks))track.mode=track.language===subtitle?"showing":"disabled"};
  const switchQuality=(next:VideoSource["label"])=>{const video=videoRef.current;if(!video||next===quality)return;pendingQualityRef.current={time:video.currentTime,playing:!video.paused};setMediaError(false);setQuality(next);setPanel(null)};
  const toggle=()=>{const video=videoRef.current;if(!video)return;video.paused?void video.play().catch(()=>setMediaError(true)):video.pause()};
  const saveProgress=(value:number)=>{setTime(value);const bucket=Math.floor(value/5);if(bucket!==lastSavedRef.current){lastSavedRef.current=bucket;localStorage.setItem(`cineyah:progress:${movie.id}`,String(value))}};
  return <div className="watch-layer" role="dialog" aria-modal="true" aria-label={`${text.nowPlaying}: ${movie.titleEn}`}>
    <button className="close player-close" onClick={onClose} aria-label={text.close}><X/></button>
    <div className="player-shell" dir="ltr"><video ref={videoRef} src={source.url} poster={movie.poster} preload="metadata" playsInline onClick={toggle} onPlay={()=>setPlaying(true)} onPause={event=>{setPlaying(false);localStorage.setItem(`cineyah:progress:${movie.id}`,String(event.currentTarget.currentTime))}} onTimeUpdate={e=>saveProgress(e.currentTarget.currentTime)} onLoadedMetadata={e=>{setDuration(e.currentTarget.duration);applySubtitle();const pending=pendingQualityRef.current;if(pending){e.currentTarget.currentTime=pending.time;if(pending.playing)void e.currentTarget.play();pendingQualityRef.current=null}}} onError={()=>setMediaError(true)} onEnded={()=>{setPlaying(false);localStorage.removeItem(`cineyah:progress:${movie.id}`)}}>{movie.subtitles.map(track=><track key={track.lang} kind="subtitles" src={track.url} srcLang={track.lang} label={locale==="ar"?track.labelAr:track.labelEn} default={track.lang==="ar"}/>)}</video>
      {mediaError&&<div className="player-error" role="alert"><strong>{locale==="ar"?"تعذر تحميل الفيديو":"Video unavailable"}</strong><p>{locale==="ar"?"قد يكون المصدر متوقفًا مؤقتًا. حاول مرة أخرى.":"The source may be temporarily unavailable. Please try again."}</p><button onClick={()=>{setMediaError(false);videoRef.current?.load()}}>{locale==="ar"?"إعادة المحاولة":"Retry"}</button></div>}
      <div className="player-title"><span>CINEYAH</span><b>{movie.titleEn}</b><small dir="rtl">{movie.titleAr}</small></div>
      <div className="player-controls"><input className="seek" aria-label={locale==="ar"?"التقدم":"Progress"} type="range" min="0" max={duration||1} value={Math.min(time,duration||1)} onChange={e=>{const next=Number(e.target.value);if(videoRef.current)videoRef.current.currentTime=next;setTime(next)}}/><div className="control-row"><button onClick={toggle} aria-label={playing?"Pause":"Play"}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><Volume2/><input aria-label="Volume" className="volume" type="range" min="0" max="1" step="0.05" value={volume} onChange={e=>{const next=Number(e.target.value);setVolume(next);if(videoRef.current)videoRef.current.volume=next}}/><span className="clock">{formatClock(time)} / {formatClock(duration)}</span><span className="control-spacer"/><button className="control-label" onClick={()=>setPanel(panel==="subs"?null:"subs")}><Captions/>{text.subtitles}</button><button className="control-label" onClick={()=>setPanel(panel==="quality"?null:"quality")}><Settings/>{quality}</button><button onClick={()=>{const video=videoRef.current;if(video&&document.pictureInPictureEnabled)void video.requestPictureInPicture()}} aria-label="Picture in Picture"><PictureInPicture/></button><button onClick={()=>{const shell=videoRef.current?.parentElement;if(shell?.requestFullscreen)void shell.requestFullscreen()}} aria-label="Fullscreen"><Expand/></button></div></div>
      {panel==="quality"&&<div className="player-popover quality-pop"><strong>{text.quality}</strong>{movie.sources.map(item=><button className={quality===item.label?"active":""} key={item.label} onClick={()=>switchQuality(item.label)}>{item.label}</button>)}</div>}
      {panel==="subs"&&<div className="player-popover subs-pop"><strong>{text.subtitles}</strong>{movie.subtitles.some(s=>s.lang==="ar")&&<button className={subtitle==="ar"?"active":""} onClick={()=>{setSubtitle("ar");setPanel(null)}}>العربية</button>}{movie.subtitles.some(s=>s.lang==="en")&&<button className={subtitle==="en"?"active":""} onClick={()=>{setSubtitle("en");setPanel(null)}}>English</button>}<button className={subtitle==="off"?"active":""} onClick={()=>{setSubtitle("off");setPanel(null)}}>{text.off}</button>{movie.subtitles.length===0&&<small>{text.noSubtitles}</small>}</div>}
    </div>
  </div>
}

function SeriesExperience({series,locale}:{series:Series;locale:Locale}){
  const text=copy[locale],[seasonNumber,setSeasonNumber]=useState(series.seasons[0]?.number??1),[episode,setEpisode]=useState<Episode|null>(null),[countdown,setCountdown]=useState<number|null>(null);
  const season=series.seasons.find(item=>item.number===seasonNumber),episodes=season?.episodes??[],episodeIndex=episode?episodes.findIndex(item=>item.id===episode.id):-1;
  useEffect(()=>{if(countdown===null)return;if(countdown<=0&&episodeIndex<episodes.length-1){setEpisode(episodes[episodeIndex+1]);setCountdown(null);return}const timer=setTimeout(()=>setCountdown(value=>value===null?null:value-1),1000);return()=>clearTimeout(timer)},[countdown,episodeIndex,episodes]);
  return <section className="series-experience" style={{"--season-accent":season?.accent??"#e72b2b"} as CSSProperties}><h2>{series.titleEn}</h2><p dir="rtl">{series.titleAr}</p><div className="season-selector" aria-label={text.seasons}>{series.seasons.map(item=><button className={item.number===seasonNumber?"active":""} key={item.number} onClick={()=>{setSeasonNumber(item.number);setEpisode(null)}}>Season {item.number}<small>الموسم {item.number}</small></button>)}</div><div className="episode-grid">{episodes.map(item=><button key={item.id} onClick={()=>setEpisode(item)}><b>Episode {item.number}</b><span>{item.titleEn}</span><small dir="rtl">{item.titleAr}</small><em>{formatDuration(item.runtimeMinutes,locale)}</em></button>)}</div>{episode&&<div className="episode-nav"><button disabled={episodeIndex<=0} onClick={()=>setEpisode(episodes[episodeIndex-1])}><ChevronLeft/>{text.previous}</button><button disabled={episodeIndex>=episodes.length-1} onClick={()=>setEpisode(episodes[episodeIndex+1])}>{text.next}<ChevronRight/></button>{countdown!==null&&<p>{text.next}: {countdown}<button onClick={()=>setCountdown(null)}>{text.close}</button></p>}</div>}</section>
}

export default function CineyahApp({locale, initialMovieId}:{locale:Locale;initialMovieId?:string}){
  const text=copy[locale],rtl=locale==="ar";
  useEffect(()=>{document.documentElement.lang=locale;document.documentElement.dir=rtl?"rtl":"ltr"},[locale,rtl]);
  const [contentType,setContentType]=useState<ContentType>("movie"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Movie|null>(publicMovies.find(movie=>movie.id===initialMovieId)??null),[watching,setWatching]=useState<Movie|null>(null),[menuOpen,setMenuOpen]=useState(false),[activeGenre,setActiveGenre]=useState<Genre|null>(null);
  const searchRef=useRef<HTMLInputElement>(null),hero=publicMovies[0];
  const switchType=(type:ContentType)=>{setContentType(type);setActiveGenre(null);setQuery("");setMenuOpen(false)};
  const content:Array<Movie|Series>=contentType==="movie"?publicMovies:seriesCatalog;
  const availableGenres=Object.keys(genreLabels) as Genre[];
  const visible=activeGenre?content.filter(item=>item.genres.includes(activeGenre)):content;
  const results=useMemo(()=>{const needle=query.trim().toLowerCase();return needle?content.filter(item=>`${item.titleAr} ${item.titleEn} ${item.year}`.toLowerCase().includes(needle)):[]},[content,query]);
  const movieRow=(label:string,items:Movie[])=>items.length?<section className="content-section"><h2>{label}</h2><div className="rail">{items.map((item,index)=><article className="tile" key={item.id} tabIndex={0} onClick={()=>setSelected(item)} onKeyDown={event=>(event.key==="Enter"||event.key===" ")&&setSelected(item)}><div className="poster-wrap"><span className="rank">{index+1}</span><img src={item.poster} alt={`${item.titleEn} — ${item.titleAr}`} loading="lazy"/>{Date.now()-new Date(item.publishedAt).getTime()<604800000&&<span className="new">{text.fresh}</span>}<button className="round-play" aria-label={text.watch} onClick={event=>{event.stopPropagation();setWatching(item)}}><Play fill="currentColor"/></button></div><h3><a href={`/${locale}/movies/${item.id}/`} onClick={event=>event.stopPropagation()}>{item.titleEn}</a></h3><p className="arabic-title" dir="rtl">{item.titleAr}</p><p className="tile-meta">{item.year} · {formatDuration(item.runtimeMinutes,locale)}</p></article>)}</div></section>:null;
  return <div className="site" dir={rtl?"rtl":"ltr"}><header className="nav"><a className="brand logo-brand" href={`/${locale}/`}><img src="/cineyah-logo.png" alt="Cineyah — سينياه"/></a><nav><button onClick={()=>switchType("movie")} className={contentType==="movie"?"active":""}>{text.movies}</button><button onClick={()=>switchType("series")} className={contentType==="series"?"active":""}>{text.series}</button></nav><div className="actions"><button onClick={()=>searchRef.current?.focus()} aria-label={contentType==="movie"?text.searchMovies:text.searchSeries}><Search/></button><a className="lang" href={locale==="ar"?"/en/":"/ar/"}><Globe2/>{locale==="ar"?"EN":"العربية"}</a><button className="menu" onClick={()=>setMenuOpen(!menuOpen)} aria-label={text.menu}><Menu/></button></div></header>{menuOpen&&<div className="mobile-menu"><button onClick={()=>switchType("movie")}>{text.movies}</button><button onClick={()=>switchType("series")}>{text.series}</button></div>}<main>
    <div className="content-switch" role="tablist" aria-label="Movies or Series"><button role="tab" aria-selected={contentType==="movie"} className={contentType==="movie"?"active":""} onClick={()=>switchType("movie")}><b>Movies</b><small>أفلام</small></button><button role="tab" aria-selected={contentType==="series"} className={contentType==="series"?"active":""} onClick={()=>switchType("series")}><b>Series</b><small>مسلسلات</small></button></div>
    {contentType==="movie"&&hero?<section className="hero" style={{backgroundImage:`linear-gradient(90deg,rgba(4,7,14,.98),rgba(4,7,14,.48),rgba(4,7,14,.92)),url('${hero.poster}')`}}><div className="hero-copy"><div className="eyebrow"><span>{text.fresh}</span>{text.legal}</div><h1>{hero.titleEn}</h1><p className="original" dir="rtl">{hero.titleAr}</p><div className="meta"><b>{hero.year}</b><b>{formatDuration(hero.runtimeMinutes,locale)}</b><b>{locale==="ar"?hero.languageAr:hero.languageEn}</b></div><p className="description">{locale==="ar"?hero.descriptionAr:hero.descriptionEn}</p><div className="hero-buttons"><button className="primary" onClick={()=>setWatching(hero)}><Play fill="currentColor"/>{text.watch}</button><button className="secondary" onClick={()=>setSelected(hero)}><Info/>{text.details}</button></div></div></section>:<section className="series-hero"><span>SERIES</span><h1>Series <small>مسلسلات</small></h1></section>}
    <div className="search-shell"><Search/><input ref={searchRef} value={query} onChange={event=>setQuery(event.target.value)} placeholder={contentType==="movie"?text.searchMovies:text.searchSeries}/>{query&&<button onClick={()=>setQuery("")} aria-label={text.close}><X/></button>}{query&&<div className="suggestions">{results.length?results.map(item=><button key={item.id} onClick={()=>{if(item.type==="movie")setSelected(item);setQuery("")}}><img src={item.poster} alt=""/><span><b>{item.titleEn}</b><small className="search-ar" dir="rtl">{item.titleAr}</small><small>{item.year} · {item.type==="movie"?text.movie:text.seriesOne}{item.type==="movie"?` · ${formatDuration(item.runtimeMinutes,locale)}`:""}</small></span><Play/></button>):<p>{contentType==="movie"?text.emptyMovies:text.emptySeries}</p>}</div>}</div>
    {availableGenres.length>0&&<Accordion type="single" collapsible className="genre-disclosure"><AccordionItem value="genres"><AccordionTrigger className="genre-trigger"><span>{rtl?"التصنيفات":"Genres"}</span><small>{activeGenre?genreLabels[activeGenre][rtl?"ar":"en"]:(rtl?"كل التصنيفات":"All genres")}</small></AccordionTrigger><AccordionContent><div className="genre-strip" aria-label={contentType==="movie"?"Movie genres":"Series genres"}><button className={!activeGenre?"active":""} onClick={()=>setActiveGenre(null)}><b>All</b><small>الكل</small></button>{availableGenres.map(key=><button key={key} className={activeGenre===key?"active":""} onClick={()=>setActiveGenre(key)}><b>{genreLabels[key].en}</b><small>{genreLabels[key].ar}</small></button>)}</div></AccordionContent></AccordionItem></Accordion>}
    {contentType==="movie"?(visible.length?movieRow(activeGenre?genreLabels[activeGenre].en:text.top,visible as Movie[]):<p className="genre-empty">{text.emptyMovies}</p>):visible.length?(visible as Series[]).map(series=><SeriesExperience key={series.id} series={series} locale={locale}/>):<div className="empty-series"><strong>Series</strong><span>مسلسلات</span><p>{text.emptySeries}</p></div>}
  </main><footer><img className="footer-logo" src="/cineyah-logo.png" alt="Cineyah"/><p>© 2026 Cineyah — سينياه</p><p>{text.legal}</p></footer>{watching&&<CineyahPlayer movie={watching} locale={locale} onClose={()=>setWatching(null)}/>} {selected&&<div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setSelected(null)}><div className="detail-modal" role="dialog" aria-modal="true"><button className="close" onClick={()=>setSelected(null)} aria-label={text.close}><X/></button><div className="modal-visual" style={{backgroundImage:`linear-gradient(0deg,#090d16,transparent),url('${selected.poster}')`}}/><div className="modal-body"><span className="type">{text.movie}</span><h2>{selected.titleEn}</h2><p className="modal-arabic-title" dir="rtl">{selected.titleAr}</p><div className="meta"><b>{selected.year}</b><b>{selected.genres.map(g=>locale==="ar"?genreLabels[g].ar:genreLabels[g].en).join(" · ")}</b><b>{formatDuration(selected.runtimeMinutes,locale)}</b></div><p>{locale==="ar"?selected.descriptionAr:selected.descriptionEn}</p><button className="primary" onClick={()=>{setSelected(null);setWatching(selected)}}><Play fill="currentColor"/>{text.watch}</button><details><summary>{text.rights}</summary><p>{selected.licenseName} — {selected.attribution}</p><a href={selected.sourceUrl} target="_blank" rel="noreferrer">{text.source}</a><a href={selected.licenseUrl} target="_blank" rel="noreferrer">{selected.licenseName}</a></details></div></div></div>}</div>;
}
