import fs from "node:fs";

const read=path=>fs.readFileSync(path,"utf8");
const catalog=read("lib/catalog.ts");
const home=read("components/movie-library-home.tsx");
const detail=read("components/movie-detail-page.tsx");
const legacy=read("components/cineyah-app.tsx");
const route=read("app/[locale]/movies/[id]/page.tsx");
const localeRoute=read("app/[locale]/page.tsx");
const nextConfig=read("next.config.ts");

const assert=(condition,message)=>{if(!condition)throw new Error(message)};
const runtimes=[...catalog.matchAll(/runtimeMinutes[":]*\s*:?\s*(\d+)/g)].map(match=>Number(match[1]));
assert(runtimes.length>=1,"No movies found in catalog");
assert(runtimes.every(minutes=>minutes>=90),`Movie catalog contains runtime below 90 minutes: ${runtimes.filter(minutes=>minutes<90).join(", ")}`);
const genreUnion=catalog.match(/export type Genre = ([^;]+);/)?.[1]??"";
assert((genreUnion.match(/\|/g)||[]).length+1===19,"Genre union must contain exactly 19 genres");
assert(home.includes("playableMovies"),"Public home must use playableMovies only");
assert(home.includes('sitePath(`/${locale}/movies/${movie.id}/`)'),"Movie cards must link to hosting-aware standalone routes");
assert(home.includes('sitePath(`/${locale}/movies/${hero.id}/`)'),"Hero action must link to hosting-aware standalone route");
assert(!home.includes("setSelected")&&!home.includes("modal-backdrop")&&!home.includes("watch-layer"),"Home must not contain preview/player overlay state");
assert(!legacy.includes("setSelected")&&!legacy.includes("watching")&&!legacy.includes("modal-backdrop"),"Legacy CineyahApp still contains overlay logic");
assert(home.includes("لا توجد مسلسلات متاحة حاليًا."),"Series accepted-empty message is missing");
assert(home.includes("التصنيفات")&&home.includes("Genres"),"Genres disclosure is missing");
assert(detail.includes("playsInline")&&detail.includes("controls"),"Native HTML5 player requirements missing");
assert(!detail.includes("crossOrigin"),"Player must not force crossOrigin");
assert(!detail.toLowerCase().includes("youtube")&&!detail.includes("<iframe"),"Player must not use YouTube or iframe playback");
assert(detail.includes("movie.sources.length>1"),"Quality controls must be gated to multiple real sources");
assert(detail.includes("movie.subtitles.map"),"Subtitle tracks must be data-driven");
assert(detail.includes("setTimeout")&&detail.includes("15000"),"Player must have a finite readiness timeout");
assert(detail.includes("sourceIndex<movie.sources.length-1")||detail.includes("sourceIndex < movie.sources.length-1"),"Player fallback must only advance through declared movie sources");
assert(!detail.includes("حقوق ومصدر المحتوى")&&!detail.includes("Rights & Content Source"),"Public movie page must not expose rights/internal source details");
assert(!detail.includes("تحقق من خيارات المشاهدة القانونية")&&!detail.includes("Check legal viewing options"),"Public movie page must not show legal-option links");
assert(!detail.includes("الجودة المتوفرة")&&!detail.includes("Available quality"),"Public movie facts must not show empty quality status");
assert(!detail.includes("الترجمة\",subtitleStatus")&&!detail.includes("Subtitles\",subtitleStatus"),"Public movie facts must not show empty subtitle status");
assert(detail.includes("أفلام مشابهة")&&detail.includes("Similar Movies")&&detail.includes("قد يعجبك أيضًا"),"Recommendation sections are missing");
assert(route.includes("generateStaticParams"),"Movie routes must be statically enumerated");
assert(localeRoute.includes("generateStaticParams"),"Locale routes must be statically enumerated for static export");
assert(nextConfig.includes('output: "export"')&&nextConfig.includes('basePath'),"Static export mode is missing");
assert(route.includes("alternates")&&route.includes("languages")&&route.includes('"@type":"Movie"'),"Movie SEO metadata/structured data missing");
console.log(JSON.stringify({movies:runtimes.length,minRuntime:Math.min(...runtimes),homePlayableOnly:true,publicRightsUi:false,noYouTubePlayer:true,hostingAwareRoutes:true},null,2));
