import fs from "node:fs";

const read=path=>fs.readFileSync(path,"utf8");
const catalog=read("lib/catalog.ts");
const publicCatalog=read("lib/public-catalog.ts");
const home=read("components/movie-library-home.tsx");
const detail=read("components/movie-detail-page.tsx");
const legacy=read("components/cineyah-app.tsx");
const route=read("app/[locale]/movies/[id]/page.tsx");
const localeRoute=read("app/[locale]/page.tsx");
const sitemap=read("app/sitemap.ts");
const nextConfig=read("next.config.ts");
const publishedReport=JSON.parse(read("content/published-report.json"));
const reviewCandidates=JSON.parse(read("content/review-candidates.json"));

const assert=(condition,message)=>{if(!condition)throw new Error(message)};
const runtimes=[...catalog.matchAll(/runtimeMinutes[":]*\s*:?\s*(\d+)/g)].map(match=>Number(match[1]));
assert(runtimes.length>=1,"No movies found in catalog");
assert(runtimes.every(minutes=>minutes>=60),`Movie catalog contains runtime below 60 minutes: ${runtimes.filter(minutes=>minutes<60).join(", ")}`);
const genreUnion=catalog.match(/export type Genre = ([^;]+);/)?.[1]??"";
assert((genreUnion.match(/\|/g)||[]).length+1===19,"Genre union must contain exactly 19 genres");
assert(new Set([...catalog.matchAll(/id:"([^"]+)"/g)].map(match=>match[1])).size===runtimes.length,"Movie IDs must be unique");
assert(publicCatalog.includes("verifiedPlayableMovieIds"),"Public catalog must require explicit playback verification");
assert(publicCatalog.includes("verifiedPlayableMovieIds.has(movie.id)"),"Public catalog must gate every title by verified playback id");
assert(publicCatalog.includes("movie.sources.length > 0"),"Public catalog must require a real playback source");
assert(publicCatalog.includes("movie.year >= 2000"),"Public catalog must reject pre-2000 titles");
assert(publicCatalog.includes("movie.runtimeMinutes >= 60"),"Public catalog must require feature runtime");
assert(publicCatalog.includes("movie.commercialUseAllowed"),"Public catalog must require commercial-use permission");
assert(publicCatalog.includes("movie.derivativesAllowed"),"Public catalog must require derivative permission for Cineyah subtitles");
assert(publicCatalog.includes('subtitle.lang === "ar"'),"Public catalog must require an Arabic subtitle track");
assert(publicCatalog.includes("isRealArtwork(movie.poster)"),"Public catalog must require a real poster");
assert(publicCatalog.includes("isRealArtwork(movie.backdrop)"),"Public catalog must require a real backdrop");
assert(publicCatalog.includes('asset.startsWith("data:")'),"Generated data-image placeholders must not count as artwork");
assert(home.includes("playableMovies"),"Public home must use playableMovies only");
assert(home.includes('from "@/lib/public-catalog"'),"Public home must source titles from the verified public catalog");
assert(home.includes('sitePath(`/${locale}/movies/${movie.id}/`)'),"Movie cards must link to hosting-aware standalone routes");
assert(home.includes('sitePath(`/${locale}/movies/${hero.id}/`)'),"Hero action must link to hosting-aware standalone route");
assert(!home.includes("setSelected")&&!home.includes("modal-backdrop")&&!home.includes("watch-layer"),"Home must not contain preview/player overlay state");
assert(!legacy.includes("setSelected")&&!legacy.includes("watching")&&!legacy.includes("modal-backdrop"),"Legacy CineyahApp still contains overlay logic");
assert(home.includes("لا توجد مسلسلات متاحة حاليًا."),"Series accepted-empty message is missing");
assert(home.includes("التصنيفات")&&home.includes("Genres"),"Genres disclosure is missing");
assert(home.includes("playableMovies.flatMap"),"Genre menu must be derived from non-empty public genres");
assert(home.includes("visibleCount")&&home.includes("Load more"),"Scalable catalog pagination is missing");
assert(detail.includes("playsInline")&&detail.includes("controls"),"Native HTML5 player requirements missing");
assert(!detail.includes("crossOrigin"),"Player must not force crossOrigin");
assert(!detail.toLowerCase().includes("youtube")&&!detail.includes("<iframe"),"Player must not use YouTube or iframe playback");
assert(detail.includes("movie.sources.length>1"),"Quality controls must be gated to multiple real sources");
assert(detail.includes("movie.subtitles.map"),"Subtitle tracks must be data-driven");
assert(detail.includes("setTimeout")&&detail.includes("15000"),"Player must have a finite readiness timeout");
assert(detail.includes("sourceIndex<movie.sources.length-1")||detail.includes("sourceIndex < movie.sources.length-1"),"Player fallback must only advance through declared movie sources");
assert(detail.includes('from "@/lib/public-catalog"'),"Recommendations must use the verified public catalog");
assert(!detail.includes("حقوق ومصدر المحتوى")&&!detail.includes("Rights & Content Source"),"Public movie page must not expose rights/internal source details");
assert(!detail.includes("تحقق من خيارات المشاهدة القانونية")&&!detail.includes("Check legal viewing options"),"Public movie page must not show legal-option links");
assert(!detail.includes("الجودة المتوفرة")&&!detail.includes("Available quality"),"Public movie facts must not show empty quality status");
assert(!detail.includes("الترجمة\",subtitleStatus")&&!detail.includes("Subtitles\",subtitleStatus"),"Public movie facts must not show empty subtitle status");
assert(detail.includes("أفلام مشابهة")&&detail.includes("Similar Movies")&&detail.includes("قد يعجبك أيضًا"),"Recommendation sections are missing");
assert(route.includes("generateStaticParams"),"Movie routes must be statically enumerated");
assert(route.includes("publicMovies")&&route.includes('from "@/lib/public-catalog"'),"Movie routes must only publish verified public titles");
assert(sitemap.includes('from "@/lib/public-catalog"'),"Sitemap must only expose verified public titles");
assert(localeRoute.includes("generateStaticParams"),"Locale routes must be statically enumerated for static export");
assert(nextConfig.includes('output: "export"')&&nextConfig.includes('basePath'),"Static export mode is missing");
assert(route.includes("alternates")&&route.includes("languages")&&route.includes('"@type":"Movie"'),"Movie SEO metadata/structured data missing");
for(const track of ["public/subtitles/valkaama-ar.vtt","public/subtitles/valkaama-en.vtt"]){
  const text=read(track);
  assert(text.startsWith("WEBVTT"),`${track} is not WebVTT`);
  assert((text.match(/-->/g)||[]).length===705,`${track} must contain all 705 cues`);
}
assert(Object.values(publishedReport.mainGenreCounts).reduce((sum,value)=>sum+value,0)===publishedReport.netPublishedMovies,"Main-genre counts must equal the net total");
assert(publishedReport.netPublishedMovies===1,"Published report must match the explicit public gate");
assert(reviewCandidates.rejectedCount===reviewCandidates.rejected.length,"Rejected candidate count is inconsistent");
assert(new Set(reviewCandidates.rejected.map(item=>item.id)).size===reviewCandidates.rejected.length,"Rejected candidate IDs must be unique");
console.log(JSON.stringify({movies:runtimes.length,minRuntime:Math.min(...runtimes),strictPublicGate:true,arabicCueCount:705,homePlayableOnly:true,publicRightsUi:false,noYouTubePlayer:true,hostingAwareRoutes:true},null,2));
